name: the_mandean_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



fonts:
  - family: Poppins
    font:
      - asset: assets/fonts/Poppins-Bold.ttf
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
        style: italic
  - family: Merriweather
    fonts:
      - asset: fonts/Merriweather-Regular.ttf
      - asset: fonts/Merriweather-Bold.ttf
      - weight: 700

version: 1.0.6+6
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  clipboard: ^0.1.3
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6
  get: ^4.6.6
  provider: ^6.1.1
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  introduction_screen: ^3.1.12
  flutter_svg: ^2.0.10+1
  convex_bottom_bar: ^3.2.0
  syncfusion_flutter_calendar: ^26.1.35
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0
  cloud_firestore: ^5.1.0
  firebase_core: ^3.1.1
  image_picker: ^1.1.2
  cached_network_image: ^3.2.2
  intl: ^0.19.0
  unicons: ^2.1.0
  story_view: ^0.16.5
  flutter_image_compress: ^2.3.0
  timeago: ^3.7.0
  flutter_spinkit: ^5.1.0
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  photo_view: ^0.15.0
  photo_gallery: ^2.2.1
  wechat_assets_picker: ^9.1.0
  image: ^4.2.0
  image_cropper: ^7.1.0
  crop_your_image: ^1.1.0
  badges: ^3.1.2
  firebase_messaging: ^15.0.4
  dotted_border: ^2.1.0
  cloud_functions: ^5.1.0
  flutter_animate: ^4.5.2
  flutter_compass: ^0.8.1
  sensors_plus: ^6.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/mandean.png
    - assets/ginzas/al-saadiENG.json
    - assets/images/darfesh2.png
    - assets/images/masbutta.jpeg
    - assets/images/hayyi.jpeg
    - assets/images/festival.jpeg
    - assets/images/texts.jpeg
    - assets/images/backgroundPhoto.jpeg
    - assets/images/darfesh1.jpeg
    - assets/ginzas/MandaeanBookOfJohn.json
    - assets/ginzas/ginzaArabic.json
    - assets/images/arabic.png
    - assets/images/english.png
    - assets/images/ginzaBook.jpg
    - assets/images/bookVector.png
    - assets/images/OnboardPicture1.jpeg
    - assets/images/OnboardPicture2.jpeg
    - assets/images/OnboardPicture3.jpeg
    - assets/images/rushama.avif
    - assets/prayers/rushama.json



