name: the_mandean_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



fonts:
  - family: Poppins
    font:
      - asset: assets/fonts/Poppins-Bold.ttf
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
        style: italic

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  clipboard: ^0.1.3
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6
  get: ^4.6.6
  provider: ^6.1.1
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  introduction_screen: ^3.1.12
  flutter_svg: ^2.0.10+1
  convex_bottom_bar: ^3.2.0
  syncfusion_flutter_calendar: ^26.1.35


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/mandean.png
    - assets/images/quran.png
    - assets/images/quran2.png
    - assets/images/namaz.png
    - assets/images/namaz2.png
    - assets/images/zakat.png
    - assets/images/zakat2.png
    - assets/images/home.png
    - assets/images/holyQuran.png
    - assets/images/community.png
    - assets/images/mosque.png
    - assets/images/calendar.png
    - assets/ginzas/al-saadiENG.json
