// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP3Qb60A_TL1MGFYIYdSdKAJBzpX95QTY',
    appId: '1:805477857271:web:684fccd43800d69564e0f2',
    messagingSenderId: '805477857271',
    projectId: 'themandaeanapp',
    authDomain: 'themandaeanapp.firebaseapp.com',
    databaseURL: 'https://themandaeanapp-default-rtdb.firebaseio.com',
    storageBucket: 'themandaeanapp.appspot.com',
    measurementId: 'G-WQP36S8ED3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_gX4f81leEziC0jO6mdKSWKlUj_fVjHQ',
    appId: '1:805477857271:android:26298086ca1f2ef864e0f2',
    messagingSenderId: '805477857271',
    projectId: 'themandaeanapp',
    databaseURL: 'https://themandaeanapp-default-rtdb.firebaseio.com',
    storageBucket: 'themandaeanapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHC14hI-EEM2e0B1rMCfdOBgdvUt3ZjAs',
    appId: '1:805477857271:ios:d1f4189f205a6d5864e0f2',
    messagingSenderId: '805477857271',
    projectId: 'themandaeanapp',
    databaseURL: 'https://themandaeanapp-default-rtdb.firebaseio.com',
    storageBucket: 'themandaeanapp.appspot.com',
    iosBundleId: 'com.example.theMandeanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHC14hI-EEM2e0B1rMCfdOBgdvUt3ZjAs',
    appId: '1:805477857271:ios:d1f4189f205a6d5864e0f2',
    messagingSenderId: '805477857271',
    projectId: 'themandaeanapp',
    databaseURL: 'https://themandaeanapp-default-rtdb.firebaseio.com',
    storageBucket: 'themandaeanapp.appspot.com',
    iosBundleId: 'com.example.theMandeanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP3Qb60A_TL1MGFYIYdSdKAJBzpX95QTY',
    appId: '1:805477857271:web:0371fc9bce19c39a64e0f2',
    messagingSenderId: '805477857271',
    projectId: 'themandaeanapp',
    authDomain: 'themandaeanapp.firebaseapp.com',
    databaseURL: 'https://themandaeanapp-default-rtdb.firebaseio.com',
    storageBucket: 'themandaeanapp.appspot.com',
    measurementId: 'G-ENP65S75TW',
  );

}